config/routes.rb
Rails.application.routes.draw do
  resources :short_urls

  root 'short_urls#index'

  get '/:id', to: 'short_urls#redirect'

end

app/models/short_url.rb
class ShortUrl < ActiveRecord::Base

  validates_presence_of :short, :if => :long?, :message => "An error occurred creating the shortened URL."
  validates_presence_of :long, :message => "You must supply a value for the original URL."
  validates_uniqueness_of :short, :long, :message => "This URL has already been shortened. Please enter a unique URL."
  format_err = "Please enter a properly formatted URL (e.g., http://www.google.com)"
  validates_format_of :short, :with => URI::regexp(%w(http https)), :if => :long?, :message => format_err
  validates_format_of :long, :with => URI::regexp(%w(http https)), :message => format_err

  before_validation do
    shorten if !self.long.blank? and self.short.blank?
  end


  def self.search(query)
    modified_query = query.gsub(/[0Oo]/, '%')  #use wild card to fulfill requirement (see Readme.rdoc)
    where("long like ? or short like ?", "%#{modified_query}%", "%#{modified_query}%")
  end


  private

  def shorten
    self.short = generate_unique_short_url(self.long)
  end

  def generate_unique_short_url(long)
    short = UrlShortener::generate_short_url(long)

    if(ShortUrl.where(short: short ).count > 0) #try again if already in database
      generate_unique_short_url(long)
    else
      ShortUrl.all.each do |url|
        if one_different_char?(short, url.short) #try again if the generated value is similar to existing value in database (see Readme.rdoc)
          generate_unique_short_url(long)
        end
      end
    end
    return short
  end

  def one_different_char?(string1, string2)
    string2_dup = string2.dup #don't modify original string
    string1.chars{|char| string2_dup.sub!(char, '')}
    string2_dup.size == 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: [:show, :edit, :update, :destroy]

  # GET /short_urls
  # GET /short_urls.json
  def index
    if params[:search]
      @short_urls = ShortUrl.search(params[:search]).order("created_at DESC")
    else
      @short_urls = ShortUrl.all.order('created_at DESC')
    end
  end

  # GET /short_urls/1
  # GET /short_urls/1.json
  def show
  end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # GET /short_urls/1/edit
  def edit
  end

  # POST /short_urls
  # POST /short_urls.json
  def create
    @short_url = ShortUrl.new(short_url_params)

    respond_to do |format|
      if @short_url.save
        format.html { redirect_to @short_url, notice: 'Short URL was successfully created.' }
        format.json { render :show, status: :created, location: @short_url }
      else
        format.html { render :new }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /short_urls/1
  # PATCH/PUT /short_urls/1.json
  def update
    respond_to do |format|
      if @short_url.update(short_url_params)
        format.html { redirect_to @short_url, notice: 'URL was successfully updated.' }
        format.json { render :show, status: :ok, location: @short_url }
      else
        format.html { render :edit }
        format.json { render json: @short_url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /short_urls/1
  # DELETE /short_urls/1.json
  def destroy
    @short_url.destroy
    respond_to do |format|
      format.html { redirect_to short_urls_url, notice: 'Short URL was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def redirect
    url = ShortUrl.where("short like ?", "%#{params[:id]}%")[0]
    redirect_to url.long
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_short_url
      @short_url = ShortUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def short_url_params
      params.require(:short_url).permit(:long, :short)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/short_urls_helper.rb
module ShortUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <!--[if lt IE 9]>
    <script src="http://html5.shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <title>URL Shortening App</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'URL SHORTENING APP', short_urls_path, class: 'navbar-brand', data: { no_turbolink: true } %>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to 'New Short URL', new_short_url_path %></li>
              <li><%= link_to 'List All URLs', short_urls_path %></li>
            </ul>
            <%= form_tag(short_urls_path, :method => "get", id: "search-form", class: "navbar-form navbar-right", role: "search") do %>
              <div class="form-group">
                <%= text_field_tag :search, params[:search], placeholder: "Search For URL", size: "40", class: "form-control"  %>
              </div>
              <%= submit_tag "Search", class: "btn btn-default" %> <%= link_to 'Clear', short_urls_path, :class => "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <div id="main">
      <% if(notice) %>
        <div class="container-fluid">
          <h4 id="notice" class="bg-success well-lg"><%= notice %></h4>
        </div>
      <% end %>
      <div class="container-fluid">
        <div>
          <%= yield %>
        </div>
      </div>
    </div>
    <footer>
      <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container-fluid">
          <div class="navbar-header">
            <span class="navbar-brand " style="color: #666666;"><%=Date.today.strftime("%Y")%> Ryan Frith</span>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/short_urls/_form.html.erb
<%= form_for(@short_url) do |f| %>
  <% if @short_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@short_url.errors.count, "error") %> prohibited this short_url from being saved:</h2>

      <ul>
        <% @short_url.errors.messages.values.each do |message| %>
          <% message.each do  |m| %>
            <li><%= m %></li>
          <% end %>
        <% end %>
      </ul>

    </div>
  <% end %>

  <div class="field">
    <%= f.label "URL To Shorten" %>
    <%= f.text_field :long, :size => "50" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Save Short URL", class: "btn btn-default" %> <%= link_to "Cancel", short_urls_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/short_urls/edit.html.erb
<h1>Editing URL <small>for <%=@short_url.short%></small></h1>

<%= render 'form' %>

app/views/short_urls/index.html.erb
<h1>Listing URLs</h1>

<% if @short_urls.empty? %>
  No URLs found.<br><br>
<% else %>
  <table class="table">
    <thead>
    <tr>
      <th colspan="1">Original URL</th>
      <th colspan="1">Shortened URL</th>
      <th colspan="1">Options</th>
    </tr>
    </thead>

    <tbody>
    <% @short_urls.each do |short_url| %>
      <tr>
        <td><%= link_to short_url.long, short_url.long, target: '_blank' %></td>
        <td><%= link_to short_url.short, short_url.short, target: '_blank' %></td>
        <td>
          <% link_to short_url do %>
            <%= icon('eye') %>
          <% end %>
          <%= link_to edit_short_url_path(short_url) do %>
            <%= icon('pencil') %>
          <% end %>
          <%= link_to short_url,  method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= icon('trash-o') %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'New Short URL', new_short_url_path, :class => "btn btn-default" %>

app/views/short_urls/new.html.erb
<h1>New Short URL</h1>
<%= render 'form' %>

app/views/short_urls/show.html.erb
<p><strong>Original URL:</strong> <%= link_to @short_url.long, @short_url.long, target: '_blank' %></p>
<p><strong>Shortened URL:</strong> <%= link_to @short_url.short, @short_url.short, target: '_blank' %></p>

<%= link_to 'Edit', edit_short_url_path(@short_url), class: "btn btn-default" %> <%= link_to 'Back', short_urls_path, class: "btn btn-default" %>